# Generated by Django 5.0 on 2024-01-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_owner_pets_alter_owner_user_alter_pet_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.DeleteModel(
            name='Adoption',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
