# Generated by Django 5.0 on 2024-01-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/profile1.png', null=True, upload_to='profile_pics'),
        ),
    ]
