# Generated by Django 5.0 on 2024-01-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_owner_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='images/profile_pics'),
        ),
    ]
