# Generated by Django 4.2.6 on 2024-01-30 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_owner_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="type",
        ),
    ]
