# Generated by Django 5.0 on 2024-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='picture',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pets_pics'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='profile_pics'),
        ),
    ]
