# Generated by Django 5.0 on 2024-01-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_pet_picture_pet_pet_pic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adoption',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
