# Generated by Django 5.0 on 2024-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pet_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile1.png', null=True, upload_to='profile_pics'),
        ),
    ]
