# Generated by Django 5.0 on 2024-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_adoption_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
